"""baseline_snapshot

Revision ID: 0b108aaef46f
Revises: 0a5473a62c34
Create Date: 2025-12-17 15:43:56.006509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b108aaef46f'
down_revision: Union[str, Sequence[str], None] = '0a5473a62c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_title'), table_name='events')
    # ### end Alembic commands ###
