"""Add impact_details to Article

Revision ID: 2f8b9a615e3a
Revises: ff70cbc7c9ec
Create Date: 2025-12-20 13:03:01.008749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f8b9a615e3a'
down_revision: Union[str, Sequence[str], None] = 'ff70cbc7c9ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('impact_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'impact_details')
    # ### end Alembic commands ###
