"""initial_schema_postgres

Revision ID: 685e3d7f7cc3
Revises: 
Create Date: 2025-12-16 21:31:42.128606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '685e3d7f7cc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('disaster_type', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('missing', sa.Integer(), nullable=True),
    sa.Column('injured', sa.Integer(), nullable=True),
    sa.Column('damage_billion_vnd', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_disaster_type'), 'events', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_events_key'), 'events', ['key'], unique=True)
    op.create_index(op.f('ix_events_last_updated_at'), 'events', ['last_updated_at'], unique=False)
    op.create_index(op.f('ix_events_province'), 'events', ['province'], unique=False)
    op.create_index(op.f('ix_events_started_at'), 'events', ['started_at'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('disaster_type', sa.String(length=32), nullable=False),
    sa.Column('province', sa.String(length=64), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('deaths', sa.Integer(), nullable=True),
    sa.Column('missing', sa.Integer(), nullable=True),
    sa.Column('injured', sa.Integer(), nullable=True),
    sa.Column('damage_billion_vnd', sa.Float(), nullable=True),
    sa.Column('agency', sa.String(length=256), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'url', name='uq_article_url')
    )
    op.create_index(op.f('ix_articles_canonical_url'), 'articles', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_articles_disaster_type'), 'articles', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_articles_domain'), 'articles', ['domain'], unique=False)
    op.create_index(op.f('ix_articles_event_id'), 'articles', ['event_id'], unique=False)
    op.create_index(op.f('ix_articles_fetched_at'), 'articles', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_articles_province'), 'articles', ['province'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_source'), 'articles', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_source'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_province'), table_name='articles')
    op.drop_index(op.f('ix_articles_fetched_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_event_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_domain'), table_name='articles')
    op.drop_index(op.f('ix_articles_disaster_type'), table_name='articles')
    op.drop_index(op.f('ix_articles_canonical_url'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_events_started_at'), table_name='events')
    op.drop_index(op.f('ix_events_province'), table_name='events')
    op.drop_index(op.f('ix_events_last_updated_at'), table_name='events')
    op.drop_index(op.f('ix_events_key'), table_name='events')
    op.drop_index(op.f('ix_events_disaster_type'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
