"""add_lat_lon_details

Revision ID: 803b98eea903
Revises: 0b108aaef46f
Create Date: 2025-12-17 15:49:48.704393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '803b98eea903'
down_revision: Union[str, Sequence[str], None] = '0b108aaef46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('lon', sa.Float(), nullable=True))
    op.add_column('events', sa.Column('details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'details')
    op.drop_column('events', 'lon')
    op.drop_column('events', 'lat')
    # ### end Alembic commands ###
