"""add token_version to user

Revision ID: b77f0cec3adc
Revises: eee6ad032d50
Create Date: 2026-01-13 11:55:33.404854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b77f0cec3adc'
down_revision: Union[str, Sequence[str], None] = 'eee6ad032d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'INCIDENT'::character varying"))
    op.alter_column('articles', 'is_broken',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'needs_verification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.drop_index('ix_article_title_trgm', table_name='articles', postgresql_using='gin')
    op.drop_index('ix_articles_is_red_alert', table_name='articles')
    op.create_index('ix_article_domain_published', 'articles', ['domain', 'published_at'], unique=False)
    op.create_index('ix_article_event_status', 'articles', ['event_id', 'status'], unique=False)
    op.create_index('ix_article_source_published', 'articles', ['source', 'published_at'], unique=False)
    op.create_index('ix_article_status_province_date', 'articles', ['status', 'province', 'published_at'], unique=False)
    op.create_index('ix_article_status_published', 'articles', ['status', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_commune'), 'articles', ['commune'], unique=False)
    op.create_index(op.f('ix_articles_is_broken'), 'articles', ['is_broken'], unique=False)
    op.create_index(op.f('ix_articles_landmark'), 'articles', ['landmark'], unique=False)
    op.create_index(op.f('ix_articles_route'), 'articles', ['route'], unique=False)
    op.create_index(op.f('ix_articles_village'), 'articles', ['village'], unique=False)
    op.drop_column('articles', 'is_red_alert')
    op.drop_column('articles', 'location_details')
    op.alter_column('crowdsourced_reports', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('crowdsourced_reports', 'lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_constraint('event_follows_user_id_fkey', 'event_follows', type_='foreignkey')
    op.drop_constraint('event_follows_event_id_fkey', 'event_follows', type_='foreignkey')
    op.create_foreign_key(None, 'event_follows', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_follows', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('events', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'INCIDENT'::character varying"))
    op.alter_column('events', 'needs_verification',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_event_title_trgm', table_name='events', postgresql_using='gin')
    op.drop_index('ix_events_is_red_alert', table_name='events')
    op.create_index('ix_event_last_updated', 'events', ['last_updated_at'], unique=False)
    op.create_index('ix_event_match_lookup', 'events', ['province', 'disaster_type', 'last_updated_at'], unique=False)
    op.create_index('ix_event_province_date', 'events', ['province', 'started_at'], unique=False)
    op.create_index('ix_event_public_filter', 'events', ['confidence', 'needs_verification', 'sources_count'], unique=False)
    op.create_index('ix_event_type_date', 'events', ['disaster_type', 'started_at'], unique=False)
    op.create_index(op.f('ix_events_commune'), 'events', ['commune'], unique=False)
    op.create_index(op.f('ix_events_landmark'), 'events', ['landmark'], unique=False)
    op.create_index(op.f('ix_events_route'), 'events', ['route'], unique=False)
    op.create_index(op.f('ix_events_village'), 'events', ['village'], unique=False)
    op.drop_column('events', 'is_red_alert')
    op.drop_column('events', 'location_details')
    op.drop_constraint('notifications_user_id_fkey', 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.drop_column('users', 'token_version')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key('notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id'])
    op.add_column('events', sa.Column('location_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('is_red_alert', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_events_village'), table_name='events')
    op.drop_index(op.f('ix_events_route'), table_name='events')
    op.drop_index(op.f('ix_events_landmark'), table_name='events')
    op.drop_index(op.f('ix_events_commune'), table_name='events')
    op.drop_index('ix_event_type_date', table_name='events')
    op.drop_index('ix_event_public_filter', table_name='events')
    op.drop_index('ix_event_province_date', table_name='events')
    op.drop_index('ix_event_match_lookup', table_name='events')
    op.drop_index('ix_event_last_updated', table_name='events')
    op.create_index('ix_events_is_red_alert', 'events', ['is_red_alert'], unique=False)
    op.create_index('ix_event_title_trgm', 'events', ['title'], unique=False, postgresql_using='gin')
    op.alter_column('events', 'needs_verification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('events', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'INCIDENT'::character varying"))
    op.drop_constraint(None, 'event_follows', type_='foreignkey')
    op.drop_constraint(None, 'event_follows', type_='foreignkey')
    op.create_foreign_key('event_follows_event_id_fkey', 'event_follows', 'events', ['event_id'], ['id'])
    op.create_foreign_key('event_follows_user_id_fkey', 'event_follows', 'users', ['user_id'], ['id'])
    op.alter_column('crowdsourced_reports', 'lon',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('crowdsourced_reports', 'lat',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('articles', sa.Column('location_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('articles', sa.Column('is_red_alert', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_articles_village'), table_name='articles')
    op.drop_index(op.f('ix_articles_route'), table_name='articles')
    op.drop_index(op.f('ix_articles_landmark'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_broken'), table_name='articles')
    op.drop_index(op.f('ix_articles_commune'), table_name='articles')
    op.drop_index('ix_article_status_published', table_name='articles')
    op.drop_index('ix_article_status_province_date', table_name='articles')
    op.drop_index('ix_article_source_published', table_name='articles')
    op.drop_index('ix_article_event_status', table_name='articles')
    op.drop_index('ix_article_domain_published', table_name='articles')
    op.create_index('ix_articles_is_red_alert', 'articles', ['is_red_alert'], unique=False)
    op.create_index('ix_article_title_trgm', 'articles', ['title'], unique=False, postgresql_using='gin')
    op.alter_column('articles', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('articles', 'needs_verification',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'is_broken',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('articles', 'stage',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'INCIDENT'::character varying"))
    # ### end Alembic commands ###
