"""add_image_url_and_missing_tables

Revision ID: eee6ad032d50
Revises: 2f8b9a615e3a
Create Date: 2026-01-07 12:59:15.117131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee6ad032d50'
down_revision: Union[str, Sequence[str], None] = '2f8b9a615e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('articles', sa.Column('image_url', sa.Text(), nullable=True))
    # op.add_column('articles', sa.Column('location_description', sa.Text(), nullable=True))
    # op.add_column('articles', sa.Column('landmark', sa.String(length=128), nullable=True))
    # op.add_column('articles', sa.Column('stage', sa.String(length=32), nullable=False, server_default="INCIDENT"))
    op.execute('ALTER TABLE articles ALTER COLUMN is_broken DROP DEFAULT')
    op.execute('ALTER TABLE articles ALTER COLUMN is_broken TYPE BOOLEAN USING is_broken::boolean')
    op.execute('ALTER TABLE articles ALTER COLUMN is_broken SET DEFAULT false')

    op.execute('ALTER TABLE articles ALTER COLUMN needs_verification DROP DEFAULT')
    op.execute('ALTER TABLE articles ALTER COLUMN needs_verification TYPE BOOLEAN USING needs_verification::boolean')
    op.execute('ALTER TABLE articles ALTER COLUMN needs_verification SET DEFAULT false')

    # op.add_column('articles', sa.Column('status', sa.String(length=20), nullable=False, server_default="approved"))
    # op.add_column('articles', sa.Column('score', sa.Float(), nullable=True))
    # op.add_column('articles', sa.Column('news_hash', sa.String(length=64), nullable=True))
    # op.alter_column('articles', 'impact_details',
    #            existing_type=sa.NUMERIC(),
    #            type_=sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'),
    #            existing_nullable=True)
    # op.alter_column('articles', 'is_red_alert',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # op.create_index('ix_article_domain_published', 'articles', ['domain', 'published_at'], unique=False)
    # op.create_index('ix_article_event_status', 'articles', ['event_id', 'status'], unique=False)
    # op.create_index('ix_article_prov_type_date', 'articles', ['province', 'disaster_type', 'published_at'], unique=False)
    # op.create_index('ix_article_source_published', 'articles', ['source', 'published_at'], unique=False)
    # op.create_index('ix_article_status_province_date', 'articles', ['status', 'province', 'published_at'], unique=False)
    # op.create_index('ix_article_status_published', 'articles', ['status', 'published_at'], unique=False)
    # op.create_index('ix_article_status_type_date', 'articles', ['status', 'disaster_type', 'published_at'], unique=False)
    # op.create_index(op.f('ix_articles_commune'), 'articles', ['commune'], unique=False)
    # op.create_index(op.f('ix_articles_is_broken'), 'articles', ['is_broken'], unique=False)
    # op.create_index(op.f('ix_articles_is_red_alert'), 'articles', ['is_red_alert'], unique=False)
    # op.create_index(op.f('ix_articles_landmark'), 'articles', ['landmark'], unique=False)
    # op.create_index(op.f('ix_articles_news_hash'), 'articles', ['news_hash'], unique=False)
    # op.create_index(op.f('ix_articles_route'), 'articles', ['route'], unique=False)
    # op.create_index(op.f('ix_articles_stage'), 'articles', ['stage'], unique=False)
    # op.create_index(op.f('ix_articles_status'), 'articles', ['status'], unique=False)
    # op.create_index(op.f('ix_articles_village'), 'articles', ['village'], unique=False)
    # op.drop_column('articles', 'risk_level')
    # op.add_column('events', sa.Column('location_description', sa.Text(), nullable=True))
    # op.add_column('events', sa.Column('landmark', sa.String(length=128), nullable=True))
    op.execute('ALTER TABLE events ALTER COLUMN needs_verification DROP DEFAULT')
    op.execute('ALTER TABLE events ALTER COLUMN needs_verification TYPE BOOLEAN USING needs_verification::boolean')
    op.execute('ALTER TABLE events ALTER COLUMN needs_verification SET DEFAULT false')
    # op.add_column('events', sa.Column('stage', sa.String(length=32), nullable=False, server_default="INCIDENT"))
    # op.add_column('events', sa.Column('lat', sa.Float(), nullable=True))
    # op.add_column('events', sa.Column('lon', sa.Float(), nullable=True))
    # op.add_column('events', sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # op.add_column('events', sa.Column('needs_verification', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # op.add_column('events', sa.Column('image_url', sa.Text(), nullable=True))
    # op.alter_column('events', 'is_red_alert',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # op.create_index('ix_event_last_updated', 'events', ['last_updated_at'], unique=False)
    # op.create_index('ix_event_match_lookup', 'events', ['province', 'disaster_type', 'last_updated_at'], unique=False)
    # op.create_index('ix_event_prov_type_date', 'events', ['province', 'disaster_type', 'started_at'], unique=False)
    # op.create_index('ix_event_province_date', 'events', ['province', 'started_at'], unique=False)
    # op.create_index('ix_event_public_filter', 'events', ['confidence', 'needs_verification', 'sources_count'], unique=False)
    # op.create_index('ix_event_type_date', 'events', ['disaster_type', 'started_at'], unique=False)
    # op.create_index(op.f('ix_events_commune'), 'events', ['commune'], unique=False)
    # op.create_index(op.f('ix_events_is_red_alert'), 'events', ['is_red_alert'], unique=False)
    # op.create_index(op.f('ix_events_landmark'), 'events', ['landmark'], unique=False)
    # op.create_index(op.f('ix_events_route'), 'events', ['route'], unique=False)
    # op.create_index(op.f('ix_events_stage'), 'events', ['stage'], unique=False)
    # op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    # op.create_index(op.f('ix_events_village'), 'events', ['village'], unique=False)
    # op.drop_column('events', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('risk_level', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_events_village'), table_name='events')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_stage'), table_name='events')
    op.drop_index(op.f('ix_events_route'), table_name='events')
    op.drop_index(op.f('ix_events_landmark'), table_name='events')
    op.drop_index(op.f('ix_events_is_red_alert'), table_name='events')
    op.drop_index(op.f('ix_events_commune'), table_name='events')
    op.drop_index('ix_event_type_date', table_name='events')
    op.drop_index('ix_event_public_filter', table_name='events')
    op.drop_index('ix_event_province_date', table_name='events')
    op.drop_index('ix_event_prov_type_date', table_name='events')
    op.drop_index('ix_event_match_lookup', table_name='events')
    op.drop_index('ix_event_last_updated', table_name='events')
    op.alter_column('events', 'is_red_alert',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'needs_verification')
    op.drop_column('events', 'details')
    op.drop_column('events', 'lon')
    op.drop_column('events', 'lat')
    op.drop_column('events', 'stage')
    op.drop_column('events', 'landmark')
    op.drop_column('events', 'location_description')
    op.add_column('articles', sa.Column('risk_level', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_articles_village'), table_name='articles')
    op.drop_index(op.f('ix_articles_status'), table_name='articles')
    op.drop_index(op.f('ix_articles_stage'), table_name='articles')
    op.drop_index(op.f('ix_articles_route'), table_name='articles')
    op.drop_index(op.f('ix_articles_news_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_landmark'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_red_alert'), table_name='articles')
    op.drop_index(op.f('ix_articles_is_broken'), table_name='articles')
    op.drop_index(op.f('ix_articles_commune'), table_name='articles')
    op.drop_index('ix_article_status_type_date', table_name='articles')
    op.drop_index('ix_article_status_published', table_name='articles')
    op.drop_index('ix_article_status_province_date', table_name='articles')
    op.drop_index('ix_article_source_published', table_name='articles')
    op.drop_index('ix_article_prov_type_date', table_name='articles')
    op.drop_index('ix_article_event_status', table_name='articles')
    op.drop_index('ix_article_domain_published', table_name='articles')
    op.alter_column('articles', 'is_red_alert',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('articles', 'impact_details',
               existing_type=sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_column('articles', 'news_hash')
    op.drop_column('articles', 'score')
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'needs_verification')
    op.drop_column('articles', 'is_broken')
    op.drop_column('articles', 'stage')
    op.drop_column('articles', 'landmark')
    op.drop_column('articles', 'location_description')
    op.drop_column('articles', 'image_url')
    # ### end Alembic commands ###
