"""remove_risk_level

Revision ID: ff70cbc7c9ec
Revises: 803b98eea903
Create Date: 2025-12-18 21:43:17.622875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff70cbc7c9ec'
down_revision: Union[str, Sequence[str], None] = '803b98eea903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_risk_level'), table_name='articles')
    op.drop_column('articles', 'risk_level')
    op.drop_index(op.f('ix_events_risk_level'), table_name='events')
    op.drop_column('events', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('risk_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_events_risk_level'), 'events', ['risk_level'], unique=False)
    op.add_column('articles', sa.Column('risk_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_articles_risk_level'), 'articles', ['risk_level'], unique=False)
    # ### end Alembic commands ###
